# Model arguments
model_name_or_path: /data/home/the/models/DeepSeek-R1-Distill-Qwen-1.5B
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./data/OpenR1-Math-220k
dataset_num_proc: 48

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: DeepSeek-R1-Distill-Qwen-1.5B-SFT
hub_strategy: every_save
learning_rate: 1.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 16384
max_steps: 500
num_train_epochs: 1
output_dir: data/DeepSeek-R1-Distill-Qwen-1.5B-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 16
per_device_train_batch_size: 8
push_to_hub: false
report_to:
- none
save_strategy: "steps"
save_steps: 500
save_total_limit: 1
seed: 42
use_liger_kernel: true
warmup_ratio: 0.05